### ISSUE TITLE
`go get github.com/mariuspass/kbd` failed

### ISSUE THREAD

**Issue by gaunthan** [mariuspass/kbd#1]
Hi. I had a problem with running `go get github.com/mariuspass/kbd`:
```go
# github.com/mariuspass/kbd
../../go/src/github.com/mariuspass/kbd/code_string.go:9: undefined: Code
../../go/src/github.com/mariuspass/kbd/code_string.go:132: undefined: Code
```
Does that mean  the code has some compiler error? Or I made a mistake?
Look forward to your advise and help. :-D

**Comment by mariuspass** [comment]
Hello, I can't reproduce the bug you encounter. Please tell me what OS and go version are you using.

**Comment by gaunthan** [comment]
Sorry for my late reply. Orz

Here are my environment details:
```
$ go version 
go1.8.4 linux/amd64
$ uname -a
Linux ocean 4.13.12-200.fc26.x86_64 #1 SMP Wed Nov 8 16:47:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mariuspass** [comment]
This library works only for Windows.

**Comment by gaunthan** [comment]
Oops...My apology. Thanks for your help.

In addition, is it just a wrapper for Win32 keyboard and mouse control?

**Comment by mariuspass** [comment]
Yes, you are right.
